name: "CI"

env:
  COVERAGE_GIT_BRANCH: "main"
  COVERAGE_SERVICE_NAME: "github-actions-ci"

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Pnpm"
        uses: "pnpm/action-setup@v2"
        with:
          version: "latest"

      - name: "Install Node.js"
        uses: "actions/setup-node@v2"
        with:
          cache: "pnpm"
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "pnpm install"

      - name: "Lint the code"
        run: "pnpm lint"

      - name: "Run the tests and generate the coverage report"
        run: "pnpm coverage"

      - name: "Upload the coverage report to Coveralls"
        uses: "coverallsapp/github-action@master"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./coverage/lcov.info"
